### ISSUE TITLE
Rotating Screen

### ISSUE THREAD

**Issue by venice1200** [vossstef/A2600Nano#16]
Hi,
I installed v1.3 on a tang nano 20k and get a rotating main screen with strange noises.
https://github.com/user-attachments/assets/7dd284dc-3d58-460c-a203-7ffa0371b5a7

The Main Scren is shown with the following parameter on my Monitor. I think the resolution is NTSC (720x480)?
![image](https://github.com/user-attachments/assets/61334391-dd42-447d-bcc4-20522d3664a5)

After a PAL rom is loaded the rotations stops and the resolution is changed to 720x576.
![image](https://github.com/user-attachments/assets/3d929799-4cf7-4ee8-892a-7a6e8402bfe3)

**Comment by vossstef** [comment]
@venice1200 another user reported for the C64 core : Unwanted noise in NTSC Video mode reported in a single specific Monitor configuration. Looks that you unfortunately are also affected from this effect. 
Could you check on another monitor ?
Will have a look over the next weeks what could be improved.

**Comment by venice1200** [comment]
Thanks for your Response!

I already tested three displays, and the "menu" rotates on all.
1) Eizo FlexScan EV2795
2) Toshiba TV 40TL868 (old)
3) Azorpa S1 Table (from Ama..)

I tried a second HDMI cable as well.

I will test another display today and a NTSC Rom as well.

Cheers

**Comment by vossstef** [comment]
@venice1200 there are a few ROM's that are not supported from the core (e.g. bank switching) and leading to total malfunction with black screen.  
There are also few ROM' that cause picture failures e.g. OSD screen moving down as the video stabilizer feature can't correct the video timings. Pls. have a try with another ROM and let me know. 
In case you saved such a particular ROM selection as default you are lost! and need to delete the a2600.ini file to get rid of the problem.

**Comment by venice1200** [comment]
Hi!
I get the Rotating Menu only if no rom is loaded.
The menu is rock stable if a rom is loaded.

I tried another monitor today, the same.

But let me set a default bin/rom and I am sure that helps

Where can i find the a2600.ini file?

Cheers

**Comment by vossstef** [comment]
The .ini file will be automatic created if you press Settings -> Save settings. Pls. make sure that you select a rom that properly works.
Maybe you missed to create a default a2600crt.bin in your root folder. The core will try to load that. See install instructions.

**Comment by vossstef** [comment]
@venice1200 maybe you are interested in my new release with mouse as paddle support. 
Have a look in the release package.
By that you can easily play like [Circus](https://en.wikipedia.org/wiki/Circus_(video_game)) or [Kaboom!](https://en.wikipedia.org/wiki/Kaboom!_(video_game))

**Comment by venice1200** [comment]
> Maybe you missed to create a default a2600crt.bin in your root folder. The core will try to load that. See install instructions.


Yes, i found this information today as it at the very end if the documentation.
I use a demo bin file with the Atari Fuji Logo and Rotating colors as boot rom.

I like it.

https://github.com/user-attachments/assets/1194d99d-77c2-43a8-9cf7-b8a7df75e825

I will try the new release later.
Currently I try to get an USB Pad working.

**Comment by venice1200** [comment]
You ask for help, what can I do?

**Comment by venice1200** [comment]
Question, does the Atari Core for the Tang 20k supports generally the Sony DS2 Controllers or is this functionality completely disabled?

**Comment by vossstef** [comment]
> You ask for help, what can I do?

I just categorized your request like that.

**Comment by vossstef** [comment]
> Question, does the Atari Core for the Tang 20k supports generally the Sony DS2 Controllers or is this functionality completely disabled?

All my cores do support wired DualShock 2 controllesr. The only cores that don't support is the Primer 25k as there are simply no FPGA pins left for that interface. TN20k support single controller and TP20k, TM60 and TM138k nowadays two pcs.

**Comment by venice1200** [comment]
Ok, cool.
Is it based on this schema (from your C64 Dokumentation).

![IMG_1542](https://github.com/user-attachments/assets/646e5a7a-2583-433e-8f20-65aae3117e06)

I ask because I solderred all the Parts for Midi onto the MiSTery Board from Till (for a possible Atari ST usage). 
Means two of the Pins are now used for Midi.

Is it possible to route the DS2 Pins to the Spare Pin Header of the MiSTery Board?
If yes, how to do this?
Is there a file where the I/O Pins are defined?

**Comment by venice1200** [comment]
Another idea is it to modify Tills Board and remove the Midi Ports and use free space for one or two DS Ports.

Will this work with your core(s)?

**Comment by vossstef** [comment]
If you don't need the midi ports then just desolder the parts that would block the DS2 signal from the MIDI interface . remove Resistor R9 and lift IC U3 pin 4

**Comment by vossstef** [comment]
> Ok, great!
> 
> Is the TN20k Version based on this schema (from your C64 Dokumentation)?
> 
> ![IMG_1542](https://private-user-images.githubusercontent.com/43762187/397096885-646e5a7a-2583-433e-8f20-65aae3117e06.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NTQwNDksIm5iZiI6MTczNDU1Mzc0OSwicGF0aCI6Ii80Mzc2MjE4Ny8zOTcwOTY4ODUtNjQ2ZTVhN2EtMjU4My00MzNlLThmMjAtNjVhYWUzMTE3ZTA2LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQyMDI5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGU3NzViOWYwOGI5YWQzNTFjY2Y5NDNjYTQyNjU3NTJmYWVlZTc1YzcwYmViNjU3ZmY4MDhjMzFjNzhhYzcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RJL7lt73gpOVy3U5ybvS8oRsi5xvdfHzX_hg5_sZCB4)
> 
> I ask because I solderred all the Parts for Midi onto the MiSTery Board from Till (for a possible Atari ST usage). Means two of the Pins are now used for Midi.
> 
> Is it possible to route the DS2 Pins to the Spare Pin Header of the MiSTery Board? If yes, how to do this? Is there a file where the I/O Pins are defined?

The TN20k VIC20, C64, A2600 pinmap should fit to the ```Sipeed Joystick to DIP``` adapter board.

**Comment by vossstef** [comment]
@venice1200 if you have an USB Gamepad like e.g. old Logitech Rumblepad 2 or older it can also be used.

**Comment by venice1200** [comment]
I will try get a used Logitech one.

But what about the idea to use the spare pins for the DS Controller?
Is the constraints file the correct location to modify the used pins?

**Comment by vossstef** [comment]
>Is the constraints file the correct location to modify the used pins?
Yes. Just have a try

**Comment by vossstef** [comment]
@venice1200  by the way the rotating screen topic due to missing a2600crt.bin should be fixed now with the 1.5 release.

**Comment by venice1200** [comment]
I will try this release later.

I got all parts together for building a DS Adapter for the "Pinheader" so I can test this as well.

I will close this issue here as it's solved.

Many Thanks for your help, have a good Christmas Time oder "eine schöne Weihnachtszeit"

**Comment by vossstef** [comment]
@venice1200 , many thanks and pls. let me know if you find further bug / problems . 
I am happy to improve the design further.
Also for you a happy X-mas !
