### ISSUE TITLE
DB9 Joystick directions are swapped

### ISSUE THREAD

**Issue by ojaksch** [vossstef/A2600Nano#5]
Yeah, I know, it's in an early stage but already great and playable, but DB9 Joystick directions Left/Right and Up/Down are swapped on my MiSTeryNano shield.

**Comment by ojaksch** [comment]
Numpad directions are also wrong:
4 - Left, but is Down
6 - Right, but is Up
8 - Up, but is Right
2 - Down, but is Left
0 - Trigger, is working

My USB gamepad (a simple one) isn't recognized, searching for another from my Retro setups.
And not to forget to mention that I'm using the FPGA companion from v1.1 ...

**Comment by vossstef** [comment]
@ojaksch , i created a pre-release 1.2 fixing D9 Joystick and Numpad Keyboard.
Pls. have a try and let me know. Thx !

**Comment by ojaksch** [comment]
Just had a try and can confirm that both (DB9 and Numpad) are working fine now! Many thanks for that fix!
Any other things I could test? DPC on Pitfall II is already done and working...

**Comment by vossstef** [comment]
@ojaksch , Thanks ! Then i will release now!

Do you plan to use homebrew games or demo's ?
Reason is that there are 2..3 mapper's (bank switching methods) that are not supported. Practically all commercial games should work.

Are you fine with the 'weird' keyboard map related to D9 Joystick use for SELECT and START ?

Can you pls. name model/type of the  USB gamepad that is not working ? I had also a problem with a XBOX 360 Pad clone. Stoneold Logitech Rumblepad is working fine.

**Comment by ojaksch** [comment]
> Do you plan to use homebrew games or demo's ? Reason is that there are 2..3 mapper's (bank switching methods) that are not supported. Practically all commercial games should work.

Not necessarily ;) Would be nice if this is getting supported sometime, specially for other users.

> Are you fine with the 'weird' keyboard map related to D9 Joystick use for SELECT and START ?

F11/Start is fine, PAGE UP/Select is a bit unfortunate imho: When in Menu and browsing through the cartridges with PgUp/PgDown, every PgUp also is passed through the core :) Either another key or a "when in OSD don't pass through keyboard presses" would be welcome.
 
> Can you pls. name model/type of the USB gamepad that is not working ? I had also a problem with a XBOX 360 Pad clone. Stoneold Logitech Rumblepad is working fine.

Tested three USB gamepads, but not yet with your C64 core and Till's ST core:
- CSL 47794 ("Gamepad for PS3/PC") - not working
- Nygacn NJP-308 - not working
- NoName Gamepad - working fine!

The first one isn't also working on MiST, the second not tested there, the 3rd one is its main controller. A 4th one from the old xbox1 is going to be tested if can find the xbox<->USB adapter.

My two other Tangs are in the wild [for testing for an upcoming article](https://forum.atari-home.de/index.php/topic,17980.msg270245.html?PHPSESSID=1suc3q0sp891tir3m3k44nm1oh#msg270245) of your and Till's work and I'm lazy to reflash the one where A2600 is running.

**Comment by ojaksch** [comment]
I'm closing this issue as topic is already fixed.
