### ISSUE TITLE
A housing for the A2600

### ISSUE THREAD

**Issue by ojaksch** [vossstef/A2600Nano#8]
Mixed and build upon [my own case](https://github.com/harbaum/MiSTeryNano/tree/main/board/misteryshield20k/housing3D) and [this one](https://www.thingiverse.com/thing:2269086/).
First print, matches fine except the "switch plate". Switches are missing for now.
I'm waiting for his okay whether it's okay use his hat or not but I think we should be fine because of the used GPL license.

![IMG_20241113_154332](https://github.com/user-attachments/assets/27a834ed-20ce-4561-ab32-a3a7e5c0c5cf)

![IMG_20241113_154450](https://github.com/user-attachments/assets/a7b41acc-0649-4569-94a6-8f75a979c306)

**Comment by vossstef** [comment]
@ojaksch , 
**looks great !!!**
It's amazing to see how the project can be used. Perfect !

Does it make sense to add 2  or 3 digital inputs to the core for push button knob functions? 
(reset, select, maybe color/sw)

**Comment by ojaksch** [comment]
We want it to be beautiful and not have it lying around as a bare object :)


> Does it make sense to add 2 or 3 digital inputs to the core for push button knob functions? (reset, select, maybe color/sw)

Absolutely sensible. No hurry, but I'm always ready for any atrocity.

**Comment by ojaksch** [comment]
Done! Switch plate and switches aren't perfect but I can't resize (shrink) them anymore...to delicate to print (at least on my still brave Anycubic i3 Mega). All VCS parts are glued together and also glued on top of the housing. But I'm very happy with that and that is the most important thing to me :)

Still waiting for permission to re-use the VCS parts before releasing.

![IMG_20241114_094728](https://github.com/user-attachments/assets/e5ced98b-5636-44ff-8a2c-492da9283525)

**Comment by ojaksch** [comment]
Merged into https://github.com/vossstef/A2600Nano/pull/13
